#!/bin/bash

arr[0]="1 x # @ % ^ & x @ ! ( ) # x ! ! # % ^ @ @ ^ U Z X X U S S A & # T ^ S B ~ ! ! ~ ! x @ ! ( ) # x ! ! # R # @ ! @ R # @ R T Q R F ~ R F "
arr[1]="x # @ c 2 & x # 4 G D S G W T # x % E R Y # x Y @ % ! ^ ! #  ^ ! % ! % ! x g d t 3  @ Y @ R ) Q @ E & _ R + S F | D H P J 1 7 5 k j r x "
arr[2]="z # x R E F Q # R # @ ! @ R # @ R T Q R F ~ R F E G # x T x ~ R E G D F G % x Y @ ^ E G Q % T Y G H D N W N Z M Z F B N V F Y # R & # "
arr[3]="c x ( ( F Y F U F ) W F I _ D + _ W F H W G | G N B : D F H E G G E G E J F E H !  x % E R Y # x Y @ % ! ^ ! #  ^ ! % ! % ! x g d t 3 y "
arr[4]="5 H G D H G x # @ E Y @ @ & # _ x R Y { @ Y @ Y @ R ) Q @ E & _ R + S F | D H P J  c 2 & x # 4 G D S G W T # x % E R Y # x Y @ % ! ^ ! "
arr[5]="o F ^ E G Q % T Y G H D N W N Z M Z F B N V F Y # R & # ^ Q # _ x + @ Y @ @ x f & x # 4 G D S G W T # x % E R Y # x Y @ % ! ^ ! #  ^ ! "
arr[6]="~ f a d a d j g a 3 2 r 3 8 3 5 y 5 1 3 2 5 9 3 y 5 1 7 5 k j r @ x @ # % # % ! #  a d j g a 3 2 r 3 8 3 5 y 5 1 3 2 5 9 3 y 5 1 7 7 & "


while [ true ]
do 
k=$(($RANDOM % 7))
echo ${arr[$k]}
echo ""
sleep 0.0
done